/**
 * Банк заданий для адаптивного теста немецкого языка.
 *
 * Каждое задание:
 *   id      — уникальный идентификатор
 *   level   — уровень CEFR (для отображения и статистики)
 *   b       — параметр сложности по модели Раша (логиты, ~ -3 … +3)
 *   skill   — навык: "gram" (грамматика), "vok" (лексика), "les" (чтение)
 *   text    — необязательный текст для чтения (показывается над вопросом)
 *   q       — формулировка вопроса (пропуск обозначен «___»)
 *   opts    — варианты ответа; ПРАВИЛЬНЫЙ ВСЕГДА ПЕРВЫЙ (перемешиваются при показе)
 */
const QUESTIONS = [
  // ─────────────────────────── A1 ───────────────────────────
  { id: "a1-01", level: "A1", b: -3.0, skill: "gram",
    q: "Ich ___ Anna.",
    opts: ["heiße", "heißt", "heißen", "heißest"] },
  { id: "a1-02", level: "A1", b: -2.9, skill: "gram",
    q: "___ kommst du? — Aus Spanien.",
    opts: ["Woher", "Wohin", "Wo", "Wann"] },
  { id: "a1-03", level: "A1", b: -2.8, skill: "gram",
    q: "Das ist ___ Buch.",
    opts: ["ein", "eine", "einen", "einem"] },
  { id: "a1-04", level: "A1", b: -2.9, skill: "gram",
    q: "Wir ___ in Berlin.",
    opts: ["wohnen", "wohnt", "wohne", "wohnst"] },
  { id: "a1-05", level: "A1", b: -2.8, skill: "vok",
    q: "Zum Frühstück esse ich ein ___.",
    opts: ["Brötchen", "Fenster", "Auto", "Sofa"] },
  { id: "a1-06", level: "A1", b: -2.7, skill: "gram",
    q: "Er ___ 25 Jahre alt.",
    opts: ["ist", "hat", "bin", "sind"] },
  { id: "a1-07", level: "A1", b: -2.5, skill: "gram",
    q: "___ du Deutsch?",
    opts: ["Sprichst", "Sprecht", "Spreche", "Sprechen"] },
  { id: "a1-08", level: "A1", b: -2.7, skill: "vok",
    q: "Das Gegenteil von „groß“ ist ___.",
    opts: ["klein", "alt", "neu", "schnell"] },
  { id: "a1-09", level: "A1", b: -2.3, skill: "gram",
    q: "Ich habe ___ Bruder.",
    opts: ["einen", "ein", "eine", "einer"] },
  { id: "a1-10", level: "A1", b: -2.6, skill: "les",
    text: "Lena wohnt in Hamburg. Sie ist Lehrerin und arbeitet in einer Schule. Am Wochenende spielt sie Tennis.",
    q: "Was macht Lena am Wochenende?",
    opts: ["Sie spielt Tennis.", "Sie arbeitet in der Schule.", "Sie fährt nach Hamburg.", "Sie lernt Deutsch."] },
  { id: "a1-11", level: "A1", b: -2.5, skill: "gram",
    q: "Wie viel ___ das?",
    opts: ["kostet", "kosten", "kostest", "koste"] },
  { id: "a1-12", level: "A1", b: -2.4, skill: "gram",
    q: "Am Sonntag ___ ich ins Kino.",
    opts: ["gehe", "gehst", "geht", "gehen"] },

  // ─────────────────────────── A2 ───────────────────────────
  { id: "a2-01", level: "A2", b: -1.6, skill: "gram",
    q: "Gestern ___ ich zu Hause geblieben.",
    opts: ["bin", "habe", "ist", "werde"] },
  { id: "a2-02", level: "A2", b: -1.8, skill: "gram",
    q: "Ich habe den Film schon ___.",
    opts: ["gesehen", "sehen", "sah", "geseht"] },
  { id: "a2-03", level: "A2", b: -1.7, skill: "gram",
    q: "Kannst du ___ bitte helfen?",
    opts: ["mir", "mich", "ich", "mein"] },
  { id: "a2-04", level: "A2", b: -1.7, skill: "gram",
    q: "Er ist ___ als sein Bruder.",
    opts: ["älter", "alt", "am ältesten", "ältere"] },
  { id: "a2-05", level: "A2", b: -1.5, skill: "vok",
    q: "Ich muss zum Arzt, weil ich ___ habe.",
    opts: ["Fieber", "Feuer", "Ferien", "Fehler"] },
  { id: "a2-06", level: "A2", b: -1.9, skill: "gram",
    q: "Ich fahre ___ dem Bus zur Arbeit.",
    opts: ["mit", "auf", "für", "gegen"] },
  { id: "a2-07", level: "A2", b: -1.4, skill: "gram",
    q: "Welcher Satz ist richtig?",
    opts: ["Ich weiß, dass er heute kommt.",
           "Ich weiß, dass er kommt heute.",
           "Ich weiß, dass kommt er heute.",
           "Ich weiß, dass er heute kommen."] },
  { id: "a2-08", level: "A2", b: -1.5, skill: "gram",
    q: "Hier ___ man nicht rauchen.",
    opts: ["darf", "will", "mag", "möchte"] },
  { id: "a2-09", level: "A2", b: -1.4, skill: "les",
    text: "Sehr geehrte Kundinnen und Kunden, unser Geschäft ist wegen Renovierung vom 3. bis zum 10. Mai geschlossen. Ab dem 11. Mai sind wir wieder für Sie da.",
    q: "Wann öffnet das Geschäft wieder?",
    opts: ["Am 11. Mai.", "Am 3. Mai.", "Am 10. Mai.", "Es bleibt geschlossen."] },
  { id: "a2-10", level: "A2", b: -1.9, skill: "vok",
    q: "Das Gegenteil von „billig“ ist ___.",
    opts: ["teuer", "schwer", "leicht", "langsam"] },
  { id: "a2-11", level: "A2", b: -1.3, skill: "gram",
    q: "Er hat keine Zeit, ___ er viel arbeiten muss.",
    opts: ["weil", "denn", "deshalb", "oder"] },
  { id: "a2-12", level: "A2", b: -1.5, skill: "gram",
    q: "Wenn es regnet, ___ wir zu Hause.",
    opts: ["bleiben", "bleibt", "bleibe", "blieb"] },

  // ─────────────────────────── B1 ───────────────────────────
  { id: "b1-01", level: "B1", b: -0.5, skill: "gram",
    q: "Wenn ich reich ___, würde ich viel reisen.",
    opts: ["wäre", "bin", "war", "sei"] },
  { id: "b1-02", level: "B1", b: -0.5, skill: "gram",
    q: "Der Brief ___ gestern geschickt.",
    opts: ["wurde", "wird", "ist", "hat"] },
  { id: "b1-03", level: "B1", b: -0.7, skill: "gram",
    q: "Ich freue mich ___ das Wochenende.",
    opts: ["auf", "über", "an", "für"] },
  { id: "b1-04", level: "B1", b: -0.3, skill: "gram",
    q: "Das ist der Mann, ___ Auto gestohlen wurde.",
    opts: ["dessen", "deren", "dem", "der"] },
  { id: "b1-05", level: "B1", b: -0.3, skill: "gram",
    q: "Er tut so, ___ er nichts wüsste.",
    opts: ["als ob", "wenn", "damit", "obwohl"] },
  { id: "b1-06", level: "B1", b: -0.7, skill: "vok",
    q: "Er hat sich bei mir für die Verspätung ___.",
    opts: ["entschuldigt", "bedankt", "beschwert", "verabschiedet"] },
  { id: "b1-07", level: "B1", b: -0.4, skill: "gram",
    q: "___ des schlechten Wetters gingen wir spazieren.",
    opts: ["Trotz", "Wegen", "Während", "Statt"] },
  { id: "b1-08", level: "B1", b: -0.8, skill: "gram",
    q: "Ich habe vor, im Sommer nach Italien ___.",
    opts: ["zu fahren", "fahren", "gefahren", "fuhr"] },
  { id: "b1-09", level: "B1", b: -0.6, skill: "gram",
    q: "Je mehr er arbeitet, ___ müder wird er.",
    opts: ["desto", "so", "je", "als"] },
  { id: "b1-10", level: "B1", b: -0.5, skill: "les",
    text: "Immer mehr Menschen in Deutschland fahren mit dem Fahrrad zur Arbeit. Das ist nicht nur gut für die Umwelt, sondern auch für die Gesundheit. Viele Städte bauen deshalb neue Radwege.",
    q: "Warum bauen viele Städte neue Radwege?",
    opts: ["Weil immer mehr Menschen mit dem Rad zur Arbeit fahren.",
           "Weil die Autos zu teuer geworden sind.",
           "Weil die Regierung es verlangt.",
           "Weil es zu wenige Busse gibt."] },
  { id: "b1-11", level: "B1", b: -0.4, skill: "vok",
    q: "Wir müssen endlich eine Entscheidung ___.",
    opts: ["treffen", "machen", "nehmen", "stellen"] },
  { id: "b1-12", level: "B1", b: -0.8, skill: "gram",
    q: "Er interessiert sich ___ Geschichte.",
    opts: ["für", "an", "auf", "über"] },

  // ─────────────────────────── B2 ───────────────────────────
  { id: "b2-01", level: "B2", b: 0.5, skill: "gram",
    q: "„Der Vertrag ist bis Freitag zu unterzeichnen.“ — Was bedeutet dieser Satz?",
    opts: ["Der Vertrag muss bis Freitag unterzeichnet werden.",
           "Der Vertrag darf bis Freitag unterzeichnet werden.",
           "Der Vertrag wurde am Freitag unterzeichnet.",
           "Der Vertrag kann nicht unterzeichnet werden."] },
  { id: "b2-02", level: "B2", b: 0.1, skill: "gram",
    q: "___ er krank war, ging er zur Arbeit.",
    opts: ["Obwohl", "Weil", "Damit", "Falls"] },
  { id: "b2-03", level: "B2", b: 0.5, skill: "gram",
    q: "Er sagte, er ___ keine Zeit. (indirekte Rede)",
    opts: ["habe", "haben", "gehabt", "hattet"] },
  { id: "b2-04", level: "B2", b: 0.4, skill: "gram",
    q: "Die ___ Kinder spielten im Garten.",
    opts: ["lachenden", "gelachten", "lachende", "gelachte"] },
  { id: "b2-05", level: "B2", b: 0.3, skill: "vok",
    q: "Der Professor wird morgen eine Rede ___.",
    opts: ["halten", "machen", "geben", "führen"] },
  { id: "b2-06", level: "B2", b: 0.5, skill: "gram",
    q: "Hätte ich das gewusst, ___ ich früher gekommen.",
    opts: ["wäre", "hätte", "würde", "war"] },
  { id: "b2-07", level: "B2", b: 0.3, skill: "vok",
    q: "Die Nachfrage nach E-Autos ist deutlich ___.",
    opts: ["gestiegen", "gestanden", "gestellt", "gestoßen"] },
  { id: "b2-08", level: "B2", b: 0.4, skill: "gram",
    q: "Er besteht ___ seiner Meinung.",
    opts: ["auf", "an", "in", "über"] },
  { id: "b2-09", level: "B2", b: 0.3, skill: "gram",
    q: "Es handelt sich ___ ein Missverständnis.",
    opts: ["um", "über", "von", "an"] },
  { id: "b2-10", level: "B2", b: 0.5, skill: "les",
    text: "Studien zeigen, dass Mehrsprachigkeit nicht nur die kognitiven Fähigkeiten fördert, sondern auch das Einfühlungsvermögen stärkt. Wer mehrere Sprachen spricht, wechselt häufiger die Perspektive und kann sich besser in andere hineinversetzen.",
    q: "Was ist laut Text ein Vorteil der Mehrsprachigkeit?",
    opts: ["Sie verbessert die Fähigkeit, sich in andere hineinzuversetzen.",
           "Sie garantiert beruflichen Erfolg.",
           "Sie macht das Reisen einfacher.",
           "Sie verhindert Missverständnisse vollständig."] },
  { id: "b2-11", level: "B2", b: 0.8, skill: "gram",
    q: "Der Zug hätte pünktlich sein ___.",
    opts: ["sollen", "gesollt", "sollte", "soll"] },
  { id: "b2-12", level: "B2", b: 0.6, skill: "vok",
    q: "„Etwas in Kauf nehmen“ bedeutet:",
    opts: ["einen Nachteil akzeptieren",
           "etwas Neues kaufen",
           "etwas entschieden ablehnen",
           "einen Preis aushandeln"] },

  // ─────────────────────────── C1 ───────────────────────────
  { id: "c1-01", level: "C1", b: 1.2, skill: "gram",
    q: "Er ging, ohne sich ___ zu haben.",
    opts: ["verabschiedet", "verabschieden", "verabschiedete", "verabschiedend"] },
  { id: "c1-02", level: "C1", b: 1.2, skill: "gram",
    q: "„Weil er krank war“ entspricht:",
    opts: ["Wegen seiner Krankheit", "Trotz seiner Krankheit",
           "Anlässlich seiner Krankheit", "Ungeachtet seiner Krankheit"] },
  { id: "c1-03", level: "C1", b: 1.5, skill: "vok",
    q: "Die Verhandlungen sind ins ___ geraten.",
    opts: ["Stocken", "Stehen", "Liegen", "Halten"] },
  { id: "c1-04", level: "C1", b: 1.4, skill: "vok",
    q: "„Jemandem reinen Wein einschenken“ bedeutet:",
    opts: ["jemandem die Wahrheit sagen", "jemandem Wein servieren",
           "jemandem schmeicheln", "jemanden betrügen"] },
  { id: "c1-05", level: "C1", b: 1.6, skill: "gram",
    q: "„Er will das Dokument nie gesehen haben.“ — Was bedeutet dieser Satz?",
    opts: ["Er behauptet, es nie gesehen zu haben.",
           "Er möchte es nie sehen.",
           "Er hat es sicher nie gesehen.",
           "Er weigert sich, es anzusehen."] },
  { id: "c1-06", level: "C1", b: 1.4, skill: "gram",
    q: "„Sie dürfte inzwischen angekommen sein.“ — Was bedeutet dieser Satz?",
    opts: ["Sie ist wahrscheinlich schon angekommen.",
           "Sie hat die Erlaubnis anzukommen.",
           "Sie ist auf keinen Fall angekommen.",
           "Sie muss sofort ankommen."] },
  { id: "c1-07", level: "C1", b: 1.5, skill: "gram",
    q: "___ aller Bemühungen scheiterte das Projekt.",
    opts: ["Ungeachtet", "Anhand", "Zwecks", "Mangels"] },
  { id: "c1-08", level: "C1", b: 1.4, skill: "vok",
    q: "Wir sollten diesen Vorschlag ernsthaft in ___ ziehen.",
    opts: ["Erwägung", "Überlegung", "Bedenken", "Ansicht"] },
  { id: "c1-09", level: "C1", b: 1.3, skill: "gram",
    q: "Es bedarf ___.",
    opts: ["einer gründlichen Prüfung", "eine gründliche Prüfung",
           "einer gründliche Prüfung", "einem gründlichen Prüfung"] },
  { id: "c1-10", level: "C1", b: 1.5, skill: "les",
    text: "Die Digitalisierung des Arbeitsmarktes wird vielfach als Bedrohung wahrgenommen, obgleich sie historisch betrachtet stets mehr Arbeitsplätze geschaffen als vernichtet hat. Entscheidend ist indes, ob es gelingt, die Beschäftigten rechtzeitig für die neu entstehenden Tätigkeitsfelder zu qualifizieren.",
    q: "Welche Aussage entspricht dem Text?",
    opts: ["Der Erfolg hängt davon ab, ob Beschäftigte rechtzeitig weiterqualifiziert werden.",
           "Die Digitalisierung hat bislang mehr Arbeitsplätze vernichtet als geschaffen.",
           "Die Beschäftigten lehnen neue Tätigkeitsfelder grundsätzlich ab.",
           "Historisch gesehen war die Digitalisierung stets eine Bedrohung."] },
  { id: "c1-11", level: "C1", b: 1.3, skill: "gram",
    q: "„Die zu klärenden Fragen“ sind Fragen, ...",
    opts: ["die geklärt werden müssen.", "die bereits geklärt wurden.",
           "die man nicht klären kann.", "die völlig klar sind."] },
  { id: "c1-12", level: "C1", b: 1.7, skill: "gram",
    q: "Er ist keineswegs dumm, ___ einer der Klügsten.",
    opts: ["vielmehr ist er", "vielmehr er ist", "vielmehr ist ihm", "vielmehr sei er"] },

  // ─────────────────────────── C2 ───────────────────────────
  { id: "c2-01", level: "C2", b: 2.3, skill: "vok",
    q: "„Mit etwas hinterm Berg halten“ bedeutet:",
    opts: ["etwas nicht offen aussprechen", "etwas laut verkünden",
           "etwas schnell vergessen", "etwas maßlos übertreiben"] },
  { id: "c2-02", level: "C2", b: 2.4, skill: "gram",
    q: "Er ließ es sich nicht ___, persönlich zu gratulieren.",
    opts: ["nehmen", "geben", "machen", "halten"] },
  { id: "c2-03", level: "C2", b: 2.2, skill: "gram",
    q: "Die Kritik prallte an ihm ___.",
    opts: ["ab", "auf", "aus", "an"] },
  { id: "c2-04", level: "C2", b: 2.1, skill: "gram",
    q: "Beinahe ___ er den Zug verpasst.",
    opts: ["hätte", "hat", "wäre", "würde"] },
  { id: "c2-05", level: "C2", b: 2.6, skill: "vok",
    q: "„Jemanden ins Bockshorn jagen“ bedeutet:",
    opts: ["jemanden einschüchtern", "jemanden überschwänglich loben",
           "jemanden aus dem Haus jagen", "jemanden im Wettlauf überholen"] },
  { id: "c2-06", level: "C2", b: 2.2, skill: "gram",
    q: "Der Antrag wurde ___ formaler Mängel abgelehnt.",
    opts: ["aufgrund", "zufolge", "anhand", "binnen"] },
  { id: "c2-07", level: "C2", b: 2.4, skill: "gram",
    q: "Dem Vernehmen ___ plant die Regierung eine Reform.",
    opts: ["nach", "laut", "gemäß", "wegen"] },
  { id: "c2-08", level: "C2", b: 2.3, skill: "vok",
    q: "„Er ist des Deutschen mächtig“ bedeutet:",
    opts: ["Er beherrscht die deutsche Sprache.",
           "Er hat in Deutschland großen Einfluss.",
           "Er ist stärker als der Deutsche.",
           "Er mag die deutsche Kultur."] },
  { id: "c2-09", level: "C2", b: 2.5, skill: "les",
    text: "Dass der öffentliche Diskurs zusehends verroht, ist weniger einer genuinen Verrohung der Gesellschaft geschuldet als vielmehr den Mechanismen medialer Aufmerksamkeitsökonomie, die der Zuspitzung den Vorzug vor der Differenzierung geben.",
    q: "Worauf führt der Autor die Verrohung des Diskurses zurück?",
    opts: ["Auf die Funktionsweise der medialen Aufmerksamkeitsökonomie.",
           "Auf eine grundsätzliche Verrohung der Gesellschaft.",
           "Auf den Mangel an öffentlichen Debatten.",
           "Auf die zunehmende Differenzierung der Medien."] },
  { id: "c2-10", level: "C2", b: 2.4, skill: "gram",
    q: "Wie dem auch ___, wir müssen weitermachen.",
    opts: ["sei", "ist", "wäre", "sein"] },
  { id: "c2-11", level: "C2", b: 2.1, skill: "gram",
    q: "„Die Unterlagen sind fristgerecht einzureichen.“ — Die Unterlagen ...",
    opts: ["müssen bis zum Termin eingereicht werden.",
           "können bei Bedarf eingereicht werden.",
           "wurden bereits termingerecht eingereicht.",
           "dürfen nicht mehr eingereicht werden."] },
  { id: "c2-12", level: "C2", b: 2.5, skill: "vok",
    q: "„Ins Hintertreffen geraten“ bedeutet:",
    opts: ["gegenüber anderen zurückfallen", "in einen Streit geraten",
           "in Vergessenheit geraten", "rückwärtsgewandt denken"] },
];

// Экспорт для Node (тесты/симуляции); в браузере — глобальное имя.
if (typeof module !== "undefined" && module.exports) {
  module.exports = { QUESTIONS };
}
